title: Study Repository
description: "Association Between COVID-19 Vaccination and Mortality in Immunocompromised Older Adults: A Population-Based Analysis"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
